### ISSUE TITLE
nice try

### ISSUE THREAD

**Issue by CookieCodezz** [scoobyluvs/ViperCracker#1]
there are too many suspicious files containing encrypted code, most pin cracker has a txt combo and the actual main.py code, so you're most likely to get your account stolen by some skided discord webhook logger inside of those suspicious base 64 strings in ViperCracker.py

**Comment by scoobyluvs** [comment]
ill post un obfuscated one instead snice u wanna act like a little bitch !

**Comment by CookieCodezz** [comment]
bro fuck you, for wasting peoples time with ur dead ass logger, you have no life and no girls
