### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by zPitachu** [scoobyluvs/ViperCracker#2]
![vvcm](https://user-images.githubusercontent.com/114113339/197359027-2f9ba1f6-ab4e-400b-9de2-5c4a73b4b202.png)

**Comment by zPitachu** [comment]
@scoobyluvs

**Comment by scoobyluvs** [comment]
cookies invaild

**Comment by zPitachu** [comment]
Cookie is valid, it working for me.
